version: '2'

services:

  zookeeper:
    image: quay.io/debezium/zookeeper:1.8
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:1.8
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  mongodb_01:
    image: quay.io/debezium/example-mongodb:1.8
    hostname: mongodb_01
    ports:
     - 27017:27017
    environment:
     - MONGODB_USER=debezium
     - MONGODB_PASSWORD=dbz
    depends_on:
      - "mongodb_02"
      - "mongodb_03"

  mongodb_02:
    image: quay.io/debezium/example-mongodb:1.8
    hostname: mongodb_02
    ports:
     - 27018:27017
    environment:
     - MONGODB_USER=debezium
     - MONGODB_PASSWORD=dbz

  mongodb_03:
    image: quay.io/debezium/example-mongodb:1.8
    hostname: mongodb_03
    ports:
     - 27019:27017
    environment:
     - MONGODB_USER=debezium
     - MONGODB_PASSWORD=dbz

  connect:
    image: quay.io/debezium/connect:1.8
    ports:
     - 8083:8083
    links:
     - kafka
     - mongodb_01
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
